Common terms search (WIP)
nhsuk/profiles-db-elastic pull request #22
Opened 2017-05-24 17:33 UTC by neilbmclaughlin

2017-06-02 00:00 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-02 08:03 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-02 08:13 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-04 07:41 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 07:46 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 08:04 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 08:38 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 08:39 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 10:46 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 12:44 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 12:48 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 12:49 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 14:06 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 14:12 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 16:19 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-05 21:46 UTC, neilbmclaughlin commented on scripts/container-tests
> +  number_of_docs=$(curl -s "http://es:9200/profiles/_count?q=*" | jq '.count')
Changed this from the inspection of the es-stats.json file as the introduction of nested fields introduces hidden documents as a consequence of the way ES indexes objects which in turn increases the document count in the stats. See [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-objects.html) for more detail.

2017-06-05 21:54 UTC, neilbmclaughlin commented on data/mapping/mapping.json
> +          "stopwords": [ "doctor", "doctors", "dr", "drs" ]
Using common titles as stop words for GP names seems reasonable as there is no need to search by them in the same way as searches by surgery name may include common terms ('The Market Surgery' vs 'Dr Doctor').

2017-06-05 21:55 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-06 21:20 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-07 07:44 UTC, st3v3nhunt requested changes
Some niggly little changes to do please. Along with some explanation for why things have been done as my understanding most likely isn't quite correct.

2017-06-07 07:44 UTC, st3v3nhunt commented on README.md
> +There are a number of sample queries in [sample-queries](./sample-queries) which can be used to query the data. (e.g  `curl -s -XPOST "http://localhost:9200/profiles/_search?pretty" -d @sample_querie
Can line breaks be added so no line is greater in length than 80 chars please?

2017-06-07 07:44 UTC, st3v3nhunt commented on README.md
> +An alternative to using `curl` for ES config and querying is [kibana](https://www.elastic.co/products/kibana)
Can line breaks be added so no line is greater in length than 80 chars please?

2017-06-07 07:44 UTC, st3v3nhunt commented on README.md
> +overridden by setting the environment variable `ES_PORT` (e.g. `ES_PORT=9201 ./scripts/start`).
Can line breaks be added so no line is greater in length than 80 chars please?

2017-06-07 07:44 UTC, st3v3nhunt commented on data/scripts/transform-data-filter.txt
> +
Is the blank line needed?

2017-06-07 07:44 UTC, st3v3nhunt commented on data/scripts/transform-data-filter.txt
> +.[] |
Can this file's extension be renamed to `jq` to make it clear it is a `jq` filter or are there other consequences to doing that?

Also, there is a rogue space at the end of line 1.

2017-06-07 07:44 UTC, st3v3nhunt commented on data/mapping/mapping.json
> +        "surgery_name_analyzer":{
How is this different from a [standard analyser](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-analyzer.html)?

2017-06-07 07:44 UTC, st3v3nhunt commented on data/mapping/mapping.json
>          "gp_name_analyzer":{
Could the `gp_name_analyzer` be a [stop analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stop-analyzer.html)?

2017-06-07 07:44 UTC, st3v3nhunt commented on data/mapping/mapping.json
> +          "stopwords": [ "doctor", "doctors", "dr", "drs" ]
Seems fair enough to add possible alternatives, however, I've not seen anything other than `dr` in the name. Searched via:
* `jq '.[].doctors' data/input/gp-data-merged.json | grep <search_term>`
The only `<search_term>` returning results is `dr`.

Does the punctuation get removed from terms like `dr.` so just adding `dr` is going to cover it? The reason I ask is there 1625 results for `jq '.[].doctors' data/input/gp-data-merged.json | grep 'Dr\.' | wc -l`

2017-06-07 07:44 UTC, st3v3nhunt commented on data/mapping/mapping.json
> +          "type": "nested",
I understand the need for setting `doctors` to be `nested` but I'm not sure the reason for the transformation in the first instance.

2017-06-07 07:44 UTC, st3v3nhunt commented on README.md
> +There are a number of sample queries in [sample-queries](./sample-queries) which can be used to query the data. (e.g  `curl -s -XPOST "http://localhost:9200/profiles/_search?pretty" -d @sample_querie
I'm a little unclear as to the point of the sample queries as they aren't all doing what `gp-finder` is doing. Can a `README` be added to the `sample-queries` directory explaining what each one is there for  and perhaps when each query might be useful to use?

2017-06-07 08:12 UTC, beseven commented
@neilbmclaughlin will pull down this today and undoubtly will have some quesitons for you a bit later

2017-06-07 08:34 UTC, neilbmclaughlin commented on data/mapping/mapping.json
> +          "stopwords": [ "doctor", "doctors", "dr", "drs" ]
I think your grep needs to be case insensitive. `jq '.[].doctors' data/input/gp-data-merged.json | grep -i 'Doctor' ` gives me matches.

ES removes full stops and commas as well as a load of non-alphanumeric characters (~,@,etc) so the gp_name_tokenizer will split 'dr. andrew smith' into ['andrew', 'smith'].

ES has a cool _analyze API to show what the ouput for a given input would be:
```
curl -XGET 'localhost:9200/profiles/_analyze?pretty' -d'
{
  "analyzer" : "gp_name_analyzer",
  "text" : "Dr. Andrew Smith"
}'
```

2017-06-07 08:42 UTC, neilbmclaughlin commented on data/scripts/transform-data-filter.txt
> +
Removed

2017-06-07 08:45 UTC, st3v3nhunt commented on data/mapping/mapping.json
> +          "stopwords": [ "doctor", "doctors", "dr", "drs" ]
Yup, my bad omitted `-i`. Is it worth adding `gp` and possibly `general` and `practitioner`? That would cover this result `General practitioner Dr Bernadette Duffy `

2017-06-07 09:45 UTC, neilbmclaughlin commented on data/mapping/mapping.json
>          "gp_name_analyzer":{
It's the custom name tokenizer which means it has to be a custom analyzer. The use of a custom tokenizer is preferred to the standard tokenizer as it handles searching for names like "O'Reilly" properly ([source](https://twitter.com/ErikRose/status/314135579266777089)).

2017-06-07 09:46 UTC, neilbmclaughlin commented on data/mapping/mapping.json
> +        "surgery_name_analyzer":{
surgery_name_analyzer is no longer used. I've removed it.

2017-06-07 09:49 UTC, neilbmclaughlin commented on data/mapping/mapping.json
> +          "type": "nested",
I think your grep needs to be case insensitive. `jq '.[].doctors' data/input/gp-data-merged.json | grep -i 'Doctor' ` gives me matches.

ES removes full stops and commas as well as a load of non-alphanumeric characters (~,@,etc) so the gp_name_tokenizer will split 'dr. andrew smith' into ['andrew', 'smith'].

ES has a cool _analyze API to show what the ouput for a given input would be:
```
curl -XGET 'localhost:9200/profiles/_analyze?pretty' -d'
{
  "analyzer" : "gp_name_analyzer",
  "text" : "Dr. Andrew Smith"
}'
```

2017-06-07 09:52 UTC, neilbmclaughlin commented on data/mapping/mapping.json
> +          "type": "nested",
Doctors needs to be nested as, with the existing string array of doctors names, a search for 'Andrew Smith' with find a match in [ 'Dr Jane Smith', 'Dr Andrew Jones'].

The problem is described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html).

2017-06-07 15:57 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-08 08:44 UTC, neilbmclaughlin commented on data/mapping/mapping.json
> +          "stopwords": [ "doctor", "doctors", "dr", "drs" ]
I'm trying to stick to the clear definition of a stop word in that they are words which occur in so many documents as to make them useless as a search term. I'd argue that handling _general_ and _practitioner_ (as well as the various spelling permutations of professor) is probably a data cleansing exercise to create a proper 'title' property.

2017-06-08 08:48 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-22.dev.beta.nhschoices.net)

2017-06-08 10:13 UTC, st3v3nhunt approved these changes
LGTM 👍

2017-06-08 10:14 UTC, merged