Feature/updates
nhsuk/profiles-db-elastic pull request #3
Opened 2017-05-05 11:09 UTC by st3v3nhunt

2017-05-12 12:12 UTC, neilbmclaughlin requested changes

2017-05-12 12:12 UTC, neilbmclaughlin commented on Dockerfile
> +RUN apt-get update && apt-get install -y \
Odd place for a line break :)
Remove or put before the `&&` to give a command per line?

2017-05-12 12:12 UTC, neilbmclaughlin commented on README.md
> +Running [`scripts/start`](scripts/start) will format
This is no longer strictly true in that the work is done inside the container now.

2017-05-12 12:12 UTC, neilbmclaughlin commented on data/scripts/load-data
> +pkill -F /tmp/pid
Maybe a comment as to why the pkill and the wait above needs to be done?

2017-05-12 12:12 UTC, neilbmclaughlin commented on data/scripts/load-data
> +curl -XPOST 127.0.0.1:9200/_bulk --data-binary @/usr/share/elasticsearch/tmp/data/output/gp-data-bulk-insert.json
The number lines of output from the bulk insert makes it unwieldy.

The response to the bulk insert is a json object which has a `took` and `errors` property as well as the `items` (see [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)).

Could the response be piped through jq to return a summary (`took`, `errors` and `item.length`?)

2017-05-12 12:12 UTC, neilbmclaughlin commented on scripts/bootstrap
> +open "https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html"
Not sure what I need to do with the information on this page. Maybe something added to the readme about these settings?

2017-05-12 12:12 UTC, neilbmclaughlin commented on Dockerfile
> +RUN /usr/share/elasticsearch/tmp/data/scripts/transform-data
💯  I think the idea of running the scripts which pre-processes the data for bulk insert within the container is a good thing.

2017-05-12 12:46 UTC, st3v3nhunt commented on Dockerfile
> +RUN apt-get update && apt-get install -y \
Following best practices https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#run

2017-05-12 15:18 UTC, st3v3nhunt commented on data/scripts/load-data
> +pkill -F /tmp/pid
Done

2017-05-12 15:19 UTC, st3v3nhunt commented on scripts/bootstrap
> +open "https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html"
Added info into `README`

2017-05-12 15:20 UTC, st3v3nhunt commented
@neilbmclaughlin feedback responded to with changes or explanatory comments

2017-05-14 21:31 UTC, neilbmclaughlin approved these changes

2017-05-14 21:31 UTC, merged