:movie_camera: Add initial ADR record
nhsuk/profiles-db-elastic pull request #32
Opened 2017-06-15 11:17 UTC by neilbmclaughlin

2017-06-15 11:23 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-15 11:52 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-15 12:51 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-15 14:45 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-15 15:00 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-15 15:31 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-19 08:44 UTC, st3v3nhunt requested changes
A few comments

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0002-use-elastic-co-docker-image.md
> +For initial proof of concept and early beta the Docker image is the quickest way of getting up and running with ES and this outweighs the concerns about the inability to change the default user/passw
The latter part of this sentence seems more like a consequence to me. Perhaps rewrite to `We will use the official Docker image provided by elastic.co`. I don't know if the bit about initial POCs and early Beta is required, especially as these things tend to no just be for that initial period.

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0002-use-elastic-co-docker-image.md
> +The inability to change default user presents a small risk. The risk is small since 1) the instance of ES will not be public facing, 2) it can be secured at the Docker container and network level and
I think the point above about having to use X-Pack to change the password is the thing that needs recording. I think this line i.e. line 23 can be removed.

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0002-use-elastic-co-docker-image.md
> +X-Pack: the included basic subscription for the included X-Pack security module does not allow the default username and passwords to be changed without paying a subscription. This will need addressin
Suggest changing `going forward` to `before the service is presented to users by default` (or some other time we deem it needs to be addressed by).

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0002-use-elastic-co-docker-image.md
> +Whilst the docker image is freely available there have been concerns raised in the ES community regarding it no longer being hosted on Docker Hub (it is now hosted on the elastic.co Docker [repo](htt
Perhaps some rewording here? It sounds like the consequence of using the elastic.co image is that there are additional challenges in managing different versions of ES compared to using the Docker hub version.

Is that actually the case? Certainly the knock on effect of having images with X-Pack baked in is a consequence that needs recording (which is done below).

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0003-bulk-load-gp-data.md
> +In the early stages of ES adoption (which predates the development of ETL processes to automatically build the GP JSON data file) the GP data mas manually added to this repo. The data is in a format
I think the context can be simplified quite a bit to something like `Other work within the same domain has created a JSON file containing all GP practices that need to be searched and exposed via ES. This datafile was originally created to be loaded into MongoDB.` (or something equally or more succinct.

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0003-bulk-load-gp-data.md
> +The use of an existing data file coupled with pre-procesing (using a `jq` script) to reshape it and subsequent bulk loading it into ES was a pragmatic move
Suggest rewording to `We will use the existing data file but reshape the data specifically to suit the needs of ES via jq (a lightweight JSON processing cli tool).` (or something similar).

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0003-bulk-load-gp-data.md
> +The data is loaded using bash scripts run within the container as part of `docker build` which means that the resulting Docker image contains ES preloaded with the GP data.
I don't think this needs to be here.

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0003-bulk-load-gp-data.md
> +The updating of the source GP data file in this repo is a manual process with no set schedule. This will likely be superceeded by the GP data ETL processors in the near future.
👍

2017-06-19 08:44 UTC, st3v3nhunt commented on doc/architecture/decisions/0003-bulk-load-gp-data.md
> +As well as reshaping the GP JSON document for bulk insert some manipulation of the properties was necessary to optimise for particular search requirements. The reshaping was carried out using `jq` as
👍

2017-06-19 17:18 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-19 17:21 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-19 19:04 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-20 06:20 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-20 06:42 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-20 06:46 UTC, neilbmclaughlin commented
@st3v3nhunt - I've reworked the ADR's in light of your comments and a re-reading of the Michael Nygard post. I've also split the decision record around usage of the ES Docker image into one for Docker usage in general and one for using the ES provided one specifically.

2017-06-20 06:49 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-20 06:50 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-21 07:08 UTC, st3v3nhunt requested changes
Looking good. Just a small typo I noticed.

2017-06-21 07:08 UTC, st3v3nhunt commented on doc/architecture/decisions/0004-bulk-load-gp-data.md
> +# 3. Build Image with GP Data
3 should be a 4

2017-06-21 15:27 UTC, neilbmclaughlin commented on doc/architecture/decisions/0004-bulk-load-gp-data.md
> +# 3. Build Image with GP Data
@st3v3nhunt fixed and ready for merge.

2017-06-21 15:30 UTC, c2s-dev commented
:rocket: deployment of profiles-db-elastic succeeded (http://profiles-db-elastic-pr-32.dev.beta.nhschoices.net)

2017-06-21 15:30 UTC, st3v3nhunt approved these changes

2017-06-21 15:30 UTC, merged